<?php

declare(strict_types=1);

require_once __DIR__.'/Database.php';
require_once __DIR__.'/Auth.php';
require_once __DIR__.'/AccessPolicy.php';
require_once __DIR__.'/AppNavigation.php';
require_once __DIR__.'/MailService.php';
require_once __DIR__.'/IdentityRolePolicy.php';

final class AccountManagementExperience
{
    private const ROUTES=['/admin/accounts','/admin/accounts/view'];
    public static function handles(string $route):bool{return in_array($route,self::ROUTES,true);}

    public static function render(string $route,string $basePath):never
    {
        Auth::startSession();$db=Database::connect(dirname(__DIR__));$user=Auth::currentUser($db);if(!$user||!AccessPolicy::canManageAccounts($user))self::forbidden();$_SESSION['accounts_csrf']??=bin2hex(random_bytes(24));
        if($_SERVER['REQUEST_METHOD']==='POST')self::handlePost($db,$user,$basePath,$route);
        $account=null;if($route==='/admin/accounts/view'){$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:0;$account=self::account($db,(int)$id);}self::page($db,$user,$basePath,$route,$account);
    }

    private static function handlePost(PDO $db,array $actor,string $basePath,string $route):never
    {
        if(!hash_equals((string)($_SESSION['accounts_csrf']??''),(string)($_POST['csrf_token']??''))){self::flash('error','Your session token expired.');self::redirect($basePath.'/admin/accounts');}
        $id=filter_input(INPUT_POST,'user_id',FILTER_VALIDATE_INT)?:0;$action=(string)($_POST['action']??'');
        try{
            if($id<1)throw new RuntimeException('Choose a valid account.');
            if($action==='invite'){
                $account=self::account($db,$id);if(!$account||empty($account['email']))throw new RuntimeException('That account needs an email address before invitation.');$token=Auth::createInvitation($db,$id,(int)$actor['id']);$link=self::absoluteUrl($basePath.'/activate?token='.$token);$_SESSION['accounts_invite_link']=$link;$text="Hi {$account['name']},\n\nYou have been invited to CTSMD Connect. Activate your account and choose a password using this private link:\n{$link}\n\nThis link expires in 7 days.\n\n— Children’s Theatre of Southern Maryland";MailService::queue($db,$id,(string)$account['email'],(string)$account['name'],'account_security','Your CTSMD Connect invitation',$text,null,'account-invite-'.$id.'-'.hash('sha256',$token));self::audit($db,(int)$actor['id'],'account.invited',$id,'Issued account invitation.');self::flash('success','Invitation created and queued for email delivery.');
            }elseif($action==='save_roles'){self::saveRoles($db,$actor,$id,(array)($_POST['role_ids']??[]));self::flash('success','Account roles updated.');
            }elseif($action==='toggle_status'){self::toggleStatus($db,$actor,$id);self::flash('success','Account availability updated.');
            }elseif($action==='membership_status'){self::setMembershipStatus($db,$actor,$id,(string)($_POST['membership_status']??''));self::flash('success','CTSMD membership approval updated.');
            }elseif($action==='add_relationship'){if(!AccessPolicy::canManagePeople($actor))throw new RuntimeException('People management permission is required.');$guardianId=filter_input(INPUT_POST,'guardian_user_id',FILTER_VALIDATE_INT)?:0;$studentId=filter_input(INPUT_POST,'student_user_id',FILTER_VALIDATE_INT)?:0;self::addRelationship($db,(int)$actor['id'],(int)$guardianId,(int)$studentId,(string)($_POST['relationship_type']??'guardian'));self::flash('success','Family relationship saved.');
            }elseif($action==='deactivate_relationship'){if(!AccessPolicy::canManagePeople($actor))throw new RuntimeException('People management permission is required.');$relationshipId=filter_input(INPUT_POST,'relationship_id',FILTER_VALIDATE_INT)?:0;self::deactivateRelationship($db,(int)$actor['id'],(int)$relationshipId);self::flash('success','Family relationship deactivated. History was retained.');
            }elseif($action==='verify_credential'){if(!AccessPolicy::canManageVolunteers($actor))throw new RuntimeException('Volunteer management permission is required.');$requirementId=filter_input(INPUT_POST,'requirement_id',FILTER_VALIDATE_INT)?:0;self::verifyCredential($db,$actor,$id,(int)$requirementId,(string)($_POST['completed_at']??''),(string)($_POST['expires_at']??''),trim((string)($_POST['note']??''))?:null);self::flash('success','Volunteer requirement verified. Shift eligibility updates immediately.');
            }else throw new RuntimeException('Choose a valid account action.');
        }catch(RuntimeException $e){self::flash('error',$e->getMessage());}
        self::redirect($basePath.'/admin/accounts/view?id='.$id);
    }

    private static function setMembershipStatus(PDO $db,array $actor,int $userId,string $status):void
    {
        if(!in_array($status,['pending','approved','denied'],true))throw new RuntimeException('Choose a valid CTSMD membership status.');
        $stmt=$db->prepare('SELECT organization_membership_status,email,CONCAT(first_name,\' \',last_name) name FROM users WHERE id=:id AND active=1 LIMIT 1');$stmt->execute(['id'=>$userId]);$before=$stmt->fetch();if(!$before)throw new RuntimeException('That account no longer exists.');
        $db->prepare('UPDATE users SET organization_membership_status=:status,organization_membership_reviewed_at=CURRENT_TIMESTAMP,organization_membership_reviewed_by_user_id=:actor WHERE id=:id')->execute(['status'=>$status,'actor'=>(int)$actor['id'],'id'=>$userId]);
        self::audit($db,(int)$actor['id'],'membership.'.$status,$userId,'Updated CTSMD organization membership approval.',['before'=>$before['organization_membership_status'],'after'=>$status]);
        if($status==='approved'&&!empty($before['email'])){try{$body="Hi {$before['name']},\n\nYour CTSMD Connect membership has been approved. You can now access CTSMD’s general member Community and organization-wide member resources. Production-specific access will appear when CTSMD adds you or your household to an active production.\n\n— Children’s Theatre of Southern Maryland";MailService::queue($db,$userId,(string)$before['email'],(string)$before['name'],'account_security','Your CTSMD Connect membership is approved',$body,null,'membership-approved-'.$userId.'-'.time());}catch(Throwable){}}
    }

    private static function saveRoles(PDO $db,array $actor,int $userId,array $roleIds):void
    {
        $ids=array_values(array_unique(array_filter(array_map('intval',$roleIds),static fn(int $id):bool=>$id>0)));$roles=self::roles($db);$allowed=array_column($roles,'id');foreach($ids as $id)if(!in_array($id,$allowed,true))throw new RuntimeException('One or more roles are invalid.');$adminRoleId=0;foreach($roles as $role)if($role['code']==='administrator')$adminRoleId=(int)$role['id'];if($userId===(int)$actor['id']&&!in_array($adminRoleId,$ids,true))throw new RuntimeException('You cannot remove your own Administrator role.');IdentityRolePolicy::assertRoleSelection($db,$userId,$ids);$db->beginTransaction();try{$before=Auth::roles($db,$userId);$db->prepare('DELETE FROM auth_user_roles WHERE user_id=:user')->execute(['user'=>$userId]);$insert=$db->prepare('INSERT INTO auth_user_roles (user_id,role_id,assigned_by_user_id) VALUES (:user,:role,:actor)');foreach($ids as $roleId)$insert->execute(['user'=>$userId,'role'=>$roleId,'actor'=>(int)$actor['id']]);self::audit($db,(int)$actor['id'],'account.roles_updated',$userId,'Updated account roles.',['before'=>$before,'after'=>Auth::roles($db,$userId)]);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();if($e instanceof RuntimeException)throw $e;throw new RuntimeException('Roles could not be updated.');}
    }

    private static function toggleStatus(PDO $db,array $actor,int $userId):void
    {
        if($userId===(int)$actor['id'])throw new RuntimeException('You cannot disable your own account.');$s=$db->prepare('SELECT account_status,password_hash FROM users WHERE id=:id LIMIT 1');$s->execute(['id'=>$userId]);$row=$s->fetch();if(!$row)throw new RuntimeException('That account no longer exists.');if($row['account_status']==='disabled'){$managed=$db->prepare("SELECT 1 FROM family_relationships fr JOIN auth_user_roles ur ON ur.user_id=fr.student_user_id JOIN auth_roles r ON r.id=ur.role_id AND r.code='student' WHERE fr.student_user_id=:user AND fr.status='active' LIMIT 1");$managed->execute(['user'=>$userId]);$next=$managed->fetchColumn()?'managed':(empty($row['password_hash'])?'invited':'active');}else{$next='disabled';}$db->prepare('UPDATE users SET account_status=:status WHERE id=:id')->execute(['status'=>$next,'id'=>$userId]);self::audit($db,(int)$actor['id'],$next==='disabled'?'account.disabled':'account.enabled',$userId,'Changed account availability.',['status'=>$next]);
    }

    private static function addRelationship(PDO $db,int $actorId,int $guardianId,int $studentId,string $type):void
    {
        if(!in_array($type,['parent','guardian','caregiver'],true))throw new RuntimeException('Choose a valid relationship type.');IdentityRolePolicy::assertFamilyPair($db,$guardianId,$studentId);
        $db->beginTransaction();try{$sql="INSERT INTO family_relationships (guardian_user_id,student_user_id,relationship_type,is_primary,status,created_by_user_id) VALUES (:guardian,:student,:relationship_type,0,'active',:actor) ON DUPLICATE KEY UPDATE relationship_type=VALUES(relationship_type),status='active',created_by_user_id=VALUES(created_by_user_id),updated_at=CURRENT_TIMESTAMP";$db->prepare($sql)->execute(['guardian'=>$guardianId,'student'=>$studentId,'relationship_type'=>$type,'actor'=>$actorId]);$idStmt=$db->prepare('SELECT id FROM family_relationships WHERE guardian_user_id=:guardian AND student_user_id=:student LIMIT 1');$idStmt->execute(['guardian'=>$guardianId,'student'=>$studentId]);$relationshipId=(int)$idStmt->fetchColumn();self::auditSubject($db,$actorId,'family.relationship_saved','family_relationship',$relationshipId,'Saved family relationship.',['guardian_user_id'=>$guardianId,'student_user_id'=>$studentId,'relationship_type'=>$type,'status'=>'active']);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();if($e instanceof RuntimeException)throw $e;throw new RuntimeException('The family relationship could not be saved.');}
    }

    private static function deactivateRelationship(PDO $db,int $actorId,int $relationshipId):void
    {
        if($relationshipId<1)throw new RuntimeException('That relationship could not be found.');$db->beginTransaction();try{$stmt=$db->prepare("SELECT id,guardian_user_id,student_user_id,relationship_type,status FROM family_relationships WHERE id=:id FOR UPDATE");$stmt->execute(['id'=>$relationshipId]);$relationship=$stmt->fetch();if(!$relationship||$relationship['status']!=='active')throw new RuntimeException('That relationship is already inactive or unavailable.');$count=$db->prepare("SELECT COUNT(DISTINCT fr.guardian_user_id) FROM family_relationships fr JOIN users guardian ON guardian.id=fr.guardian_user_id AND guardian.active=1 AND guardian.account_status<>'disabled' WHERE fr.student_user_id=:student AND fr.status='active'");$count->execute(['student'=>(int)$relationship['student_user_id']]);if((int)$count->fetchColumn()<=1)throw new RuntimeException('A live Student must retain at least one available parent, guardian, or caregiver. Add another guardian before deactivating this relationship.');$update=$db->prepare("UPDATE family_relationships SET status='inactive',updated_at=CURRENT_TIMESTAMP WHERE id=:id AND status='active'");$update->execute(['id'=>$relationshipId]);if($update->rowCount()<1)throw new RuntimeException('That relationship is already inactive or unavailable.');self::auditSubject($db,$actorId,'family.relationship_deactivated','family_relationship',$relationshipId,'Deactivated family relationship.',['guardian_user_id'=>(int)$relationship['guardian_user_id'],'student_user_id'=>(int)$relationship['student_user_id'],'relationship_type'=>$relationship['relationship_type'],'status'=>'inactive']);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();if($e instanceof RuntimeException)throw $e;throw new RuntimeException('The family relationship could not be deactivated.');}
    }

    private static function verifyCredential(PDO $db,array $actor,int $userId,int $requirementId,string $completed,string $expires,?string $note):void
    {
        if($userId<1||$requirementId<1)throw new RuntimeException('Choose a volunteer and requirement.');$vol=$db->prepare("SELECT u.id,CONCAT(u.first_name,' ',u.last_name) name FROM users u JOIN volunteer_profiles vp ON vp.user_id=u.id AND vp.active=1 WHERE u.id=:user AND u.active=1 AND u.account_status='active' LIMIT 1");$vol->execute(['user'=>$userId]);$volunteer=$vol->fetch();if(!$volunteer)throw new RuntimeException('That person does not have an active volunteer profile.');$req=$db->prepare('SELECT id,code,name,category,expires FROM volunteer_requirements WHERE id=:id LIMIT 1');$req->execute(['id'=>$requirementId]);$requirement=$req->fetch();if(!$requirement)throw new RuntimeException('That volunteer requirement no longer exists.');$completedDate=DateTimeImmutable::createFromFormat('Y-m-d',trim($completed));if(!$completedDate)throw new RuntimeException('Choose the date the requirement was completed or verified.');$expiresAt=null;if(trim($expires)!==''){$expiry=DateTimeImmutable::createFromFormat('Y-m-d',trim($expires));if(!$expiry)throw new RuntimeException('Enter a valid expiration date.');if($expiry<$completedDate)throw new RuntimeException('Expiration cannot be before the completion date.');$expiresAt=$expiry->format('Y-m-d 23:59:59');}if((bool)$requirement['expires']&&$expiresAt===null)throw new RuntimeException($requirement['name'].' is defined as expiring. Enter an expiration date.');if($note!==null&&mb_strlen($note)>1000)throw new RuntimeException('Keep verification notes under 1,000 characters.');
        $db->beginTransaction();try{$beforeStmt=$db->prepare('SELECT id,status,completed_at,expires_at,verified_by_user_id FROM volunteer_credentials WHERE user_id=:user AND requirement_id=:requirement FOR UPDATE');$beforeStmt->execute(['user'=>$userId,'requirement'=>$requirementId]);$before=$beforeStmt->fetch();$stmt=$db->prepare("INSERT INTO volunteer_credentials (user_id,requirement_id,status,completed_at,expires_at,verified_by_user_id) VALUES (:user,:requirement,'approved',:completed,:expires,:verifier) ON DUPLICATE KEY UPDATE status='approved',completed_at=VALUES(completed_at),expires_at=VALUES(expires_at),verified_by_user_id=VALUES(verified_by_user_id)");$stmt->execute(['user'=>$userId,'requirement'=>$requirementId,'completed'=>$completedDate->format('Y-m-d 12:00:00'),'expires'=>$expiresAt,'verifier'=>(int)$actor['id']]);$credentialId=$before?(int)$before['id']:(int)$db->lastInsertId();self::auditSubject($db,(int)$actor['id'],'volunteer.credential_verified','volunteer_credential',$credentialId,'Verified volunteer eligibility requirement.',['volunteer_user_id'=>$userId,'volunteer_name'=>$volunteer['name'],'requirement_id'=>$requirementId,'requirement_code'=>$requirement['code'],'requirement_name'=>$requirement['name'],'before'=>$before?:null,'completed_at'=>$completedDate->format('Y-m-d'),'expires_at'=>$expiresAt,'note'=>$note]);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();if($e instanceof RuntimeException)throw $e;throw new RuntimeException('The volunteer requirement verification could not be saved.');}
    }

    private static function accounts(PDO $db):array{return $db->query("SELECT u.id,CONCAT(u.first_name,' ',u.last_name) name,u.email,u.initials,u.display_role,u.account_status,u.organization_membership_status,u.last_login_at,GROUP_CONCAT(r.name ORDER BY r.name SEPARATOR ', ') role_names FROM users u LEFT JOIN auth_user_roles ur ON ur.user_id=u.id LEFT JOIN auth_roles r ON r.id=ur.role_id WHERE u.active=1 GROUP BY u.id,u.first_name,u.last_name,u.email,u.initials,u.display_role,u.account_status,u.organization_membership_status,u.last_login_at ORDER BY FIELD(u.organization_membership_status,'pending','denied','approved'),u.last_name,u.first_name")->fetchAll();}
    private static function account(PDO $db,int $id):?array{if($id<1)return null;$s=$db->prepare("SELECT id,CONCAT(first_name,' ',last_name) name,email,initials,display_role,account_status,organization_membership_status,organization_membership_reviewed_at,last_login_at,password_changed_at FROM users WHERE id=:id AND active=1 LIMIT 1");$s->execute(['id'=>$id]);$a=$s->fetch();if(!$a)return null;$a['roles']=Auth::roles($db,$id);return $a;}
    private static function roles(PDO $db):array{return $db->query("SELECT id,code,name,description FROM auth_roles WHERE active=1 ORDER BY FIELD(code,'administrator','production_staff','moderator','safeguarding','volunteer','member','student'),name")->fetchAll();}
    private static function relationshipCandidates(PDO $db,int $excludeId):array{$s=$db->prepare("SELECT u.id,CONCAT(u.first_name,' ',u.last_name) name,u.display_role role,EXISTS(SELECT 1 FROM auth_user_roles ur JOIN auth_roles r ON r.id=ur.role_id AND r.active=1 AND r.code='student' WHERE ur.user_id=u.id) is_student FROM users u WHERE u.active=1 AND u.account_status<>'disabled' AND u.id<>:exclude ORDER BY u.last_name,u.first_name");$s->execute(['exclude'=>$excludeId]);return$s->fetchAll();}
    private static function relationships(PDO $db,int $userId,bool $isStudent):array{if($isStudent){$s=$db->prepare("SELECT fr.id relationship_id,fr.relationship_type,fr.is_primary,u.id,CONCAT(u.first_name,' ',u.last_name) name,u.display_role role FROM family_relationships fr JOIN users u ON u.id=fr.guardian_user_id WHERE fr.student_user_id=:user AND fr.status='active' AND u.active=1 AND u.account_status<>'disabled' ORDER BY fr.is_primary DESC,u.last_name,u.first_name");}else{$s=$db->prepare("SELECT fr.id relationship_id,fr.relationship_type,fr.is_primary,u.id,CONCAT(u.first_name,' ',u.last_name) name,u.display_role role FROM family_relationships fr JOIN users u ON u.id=fr.student_user_id WHERE fr.guardian_user_id=:user AND fr.status='active' AND u.active=1 AND u.account_status<>'disabled' ORDER BY fr.is_primary DESC,u.last_name,u.first_name");}$s->execute(['user'=>$userId]);return$s->fetchAll();}
    private static function volunteerProfile(PDO $db,int $userId):bool{$s=$db->prepare('SELECT 1 FROM volunteer_profiles WHERE user_id=:user AND active=1 LIMIT 1');$s->execute(['user'=>$userId]);return(bool)$s->fetchColumn();}
    private static function requirements(PDO $db):array{return$db->query('SELECT id,name,category,expires FROM volunteer_requirements ORDER BY category,name')->fetchAll();}
    private static function credentials(PDO $db,int $userId):array{$s=$db->prepare("SELECT vc.id,vc.status,vc.completed_at,vc.expires_at,vr.name,vr.category,vr.expires,CONCAT(verifier.first_name,' ',verifier.last_name) verifier_name FROM volunteer_credentials vc JOIN volunteer_requirements vr ON vr.id=vc.requirement_id LEFT JOIN users verifier ON verifier.id=vc.verified_by_user_id WHERE vc.user_id=:user ORDER BY vr.category,vr.name");$s->execute(['user'=>$userId]);return$s->fetchAll();}

    private static function page(PDO $db,array $user,string $basePath,string $route,?array $account):never
    {
        $url=static fn(string $p):string=>($basePath?:'').$p;$e=static fn(string $v):string=>htmlspecialchars($v,ENT_QUOTES,'UTF-8');$flash=$_SESSION['accounts_flash']??null;$invite=$_SESSION['accounts_invite_link']??null;unset($_SESSION['accounts_flash'],$_SESSION['accounts_invite_link']);$roles=self::roles($db);$accounts=self::accounts($db);$canPeople=AccessPolicy::canManagePeople($user);$canVolunteer=AccessPolicy::canManageVolunteers($user);header('Content-Type:text/html; charset=utf-8');?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Account & Access · CTSMD Connect</title><link rel="stylesheet" href="<?=$url('/assets/css/app.css')?>"><link rel="stylesheet" href="<?=$url('/assets/css/unified-navigation.css')?>"><link rel="stylesheet" href="<?=$url('/assets/css/account-access.css')?>"></head><body class="app-body"><div class="unified-shell"><?php AppNavigation::renderSidebar($route,$basePath,$user);?><main class="unified-main"><?php AppNavigation::renderHeader('Administration',$account?$account['name']:'Account & Access',$basePath);?><div class="acct-page"><?php if($flash):?><div class="acct-flash <?=$e($flash['type'])?>"><?=$e($flash['message'])?></div><?php endif;?><?php if($invite):?><section class="acct-invite"><small>ACTIVATION LINK · ALSO QUEUED FOR EMAIL</small><code><?=$e($invite)?></code></section><?php endif;?>
        <?php if($route==='/admin/accounts'):?><section class="acct-hero"><small>PEOPLE + FAMILY + ACCESS</small><h2>One record for the person behind the account.</h2><p>Manage CTSMD membership, sign-in authority, family safeguarding relationships, and volunteer readiness from the individual account record.</p></section><div class="acct-list"><?php foreach($accounts as $a):?><a href="<?=$url('/admin/accounts/view?id='.(int)$a['id'])?>"><span class="acct-avatar"><?=$e($a['initials'])?></span><span><b><?=$e($a['name'])?></b><small><?=$e($a['email']?:'Guardian-managed profile · no login email')?></small><em><?=$e(($a['role_names']?:'No RBAC roles').' · CTSMD '.ucfirst($a['organization_membership_status']))?></em></span><strong class="<?=$e($a['account_status'])?>"><?=$e(ucwords(str_replace('_',' ',$a['account_status'])))?></strong></a><?php endforeach;?></div>
        <?php elseif(!$account):?><section class="acct-empty"><h2>Account not found.</h2><a href="<?=$url('/admin/accounts')?>">Back to accounts</a></section>
        <?php else: $accountId=(int)$account['id'];$isStudent=IdentityRolePolicy::isStudent($db,$accountId);$links=$canPeople?self::relationships($db,$accountId,$isStudent):[];$candidates=$canPeople?self::relationshipCandidates($db,$accountId):[];$isVolunteer=$canVolunteer?self::volunteerProfile($db,$accountId):false;$requirements=$canVolunteer?self::requirements($db):[];$credentials=$canVolunteer?self::credentials($db,$accountId):[];$today=date('Y-m-d');?><section class="acct-head"><div><small><?=$e(strtoupper(str_replace('_',' ',$account['account_status'])))?></small><h2><?=$e($account['name'])?></h2><p><?=$e($account['email']?:'Guardian-managed profile · no login email')?> · <?=$e($account['display_role'])?></p></div><a href="<?=$url('/admin/accounts')?>">← All accounts</a></section>
        <div class="acct-layout"><section class="acct-panel acct-access-panel"><div class="acct-panel-heading"><small>MEMBERSHIP & AUTHORIZATION</small><h3>Access</h3><p>Membership controls general CTSMD access. Roles grant administrative authority.</p></div><div class="acct-block"><h4>CTSMD membership</h4><form method="post"><input type="hidden" name="csrf_token" value="<?=$e((string)$_SESSION['accounts_csrf'])?>"><input type="hidden" name="user_id" value="<?=$accountId?>"><label>Membership status<select name="membership_status"><?php foreach(['pending','approved','denied'] as $status):?><option value="<?=$status?>"<?=$account['organization_membership_status']===$status?' selected':''?>><?=ucfirst($status)?></option><?php endforeach;?></select></label><button name="action" value="membership_status" type="submit">Update membership</button></form></div><div class="acct-divider"></div><div class="acct-block"><h4>Authorization roles</h4><div class="acct-role-list"><form method="post"><input type="hidden" name="csrf_token" value="<?=$e((string)$_SESSION['accounts_csrf'])?>"><input type="hidden" name="user_id" value="<?=$accountId?>"><?php foreach($roles as $role):?><label class="acct-role"><input type="checkbox" name="role_ids[]" value="<?=(int)$role['id']?>"<?=in_array($role['code'],$account['roles'],true)?' checked':''?>><span><b><?=$e($role['name'])?></b><small><?=$e((string)$role['description'])?></small></span></label><?php endforeach;?><button name="action" value="save_roles" type="submit">Save roles</button></form></div></div></section>
        <aside class="acct-rail"><section class="acct-panel acct-lifecycle"><div class="acct-panel-heading"><small>ACCOUNT</small><h3>Lifecycle</h3></div><dl><div><dt>Sign-in</dt><dd><?=$e(ucwords(str_replace('_',' ',$account['account_status'])))?></dd></div><div><dt>CTSMD membership</dt><dd><?=$e(ucfirst($account['organization_membership_status']))?></dd></div><div><dt>Last login</dt><dd><?=$account['last_login_at']?$e(date('M j, Y · g:i A',strtotime($account['last_login_at']))):'Never'?></dd></div></dl><?php if($account['email']&&$account['account_status']!=='managed'):?><form method="post"><input type="hidden" name="csrf_token" value="<?=$e((string)$_SESSION['accounts_csrf'])?>"><input type="hidden" name="user_id" value="<?=$accountId?>"><button name="action" value="invite" type="submit">Issue new invitation</button></form><?php endif;?><?php if($accountId!==(int)$user['id']):?><form method="post"><input type="hidden" name="csrf_token" value="<?=$e((string)$_SESSION['accounts_csrf'])?>"><input type="hidden" name="user_id" value="<?=$accountId?>"><button class="danger" name="action" value="toggle_status" type="submit"><?=$account['account_status']==='disabled'?'Enable account':'Disable account'?></button></form><?php endif;?></section>
        <?php if($canPeople):?><section class="acct-panel acct-family-card"><div class="acct-panel-heading"><small>FAMILY & SAFEGUARDING</small><h3><?=$isStudent?'Guardian relationships':'Family relationships'?></h3><p><?=$isStudent?'Adults linked to this student provide guardian context for safeguarded communication.':'Students linked here inherit this adult’s guardian context.'?></p></div><div class="acct-family-list"><h4><?=$isStudent?'Guardians & caregivers':'Linked students'?></h4><?php if($links):?><div class="acct-records"><?php foreach($links as $link):?><article class="acct-record compact"><span><b><?=$e((string)$link['name'])?></b><small><?=$e(ucfirst((string)$link['relationship_type']))?><?=$link['is_primary']?' · Primary':''?></small></span><form method="post"><input type="hidden" name="csrf_token" value="<?=$e((string)$_SESSION['accounts_csrf'])?>"><input type="hidden" name="user_id" value="<?=$accountId?>"><input type="hidden" name="relationship_id" value="<?=(int)$link['relationship_id']?>"><button class="secondary" name="action" value="deactivate_relationship" type="submit">Deactivate</button></form></article><?php endforeach;?></div><?php else:?><div class="acct-empty-state"><b>No active links</b><span>No family relationships are recorded for this person.</span></div><?php endif;?></div><details class="acct-add-family"><summary><?=$isStudent?'Link a guardian':'Link a student'?></summary><form method="post"><input type="hidden" name="csrf_token" value="<?=$e((string)$_SESSION['accounts_csrf'])?>"><input type="hidden" name="user_id" value="<?=$accountId?>"><?php if($isStudent):?><input type="hidden" name="student_user_id" value="<?=$accountId?>"><label>Guardian<select name="guardian_user_id" required><option value="">Choose person</option><?php foreach($candidates as $candidate):if((bool)$candidate['is_student'])continue;?><option value="<?=(int)$candidate['id']?>"><?=$e($candidate['name'].' · '.$candidate['role'])?></option><?php endforeach;?></select></label><?php else:?><input type="hidden" name="guardian_user_id" value="<?=$accountId?>"><label>Student<select name="student_user_id" required><option value="">Choose student</option><?php foreach($candidates as $candidate):if(!(bool)$candidate['is_student'])continue;?><option value="<?=(int)$candidate['id']?>"><?=$e((string)$candidate['name'])?></option><?php endforeach;?></select></label><?php endif;?><label>Relationship<select name="relationship_type"><option value="parent">Parent</option><option value="guardian">Guardian</option><option value="caregiver">Caregiver</option></select></label><button name="action" value="add_relationship" type="submit">Save relationship</button></form><p class="acct-muted">Links are deactivated, not deleted, so safeguarding history stays traceable.</p></details></section><?php endif;?></aside></div>
        <?php if($canVolunteer):?><section class="acct-panel acct-readiness"><header class="acct-section-head"><div><small>VOLUNTEER ELIGIBILITY</small><h3>Readiness & training</h3></div><p>Verified requirements determine whether this person can register for restricted volunteer shifts.</p></header><?php if(!$isVolunteer):?><div class="acct-empty-state readiness"><b>No active volunteer profile</b><span>Eligibility credentials can be recorded once this person has an active volunteer profile.</span><a href="<?=$url('/admin/volunteer-development')?>">Open volunteer development →</a></div><?php else:?><div class="acct-readiness-grid"><div class="acct-credential-column"><div class="acct-subhead"><div><h4>Current credentials</h4><p><?=count($credentials)?> recorded requirement<?=count($credentials)===1?'':'s'?></p></div></div><?php if($credentials):?><div class="acct-records credential-list"><?php foreach($credentials as $credential):$expired=!empty($credential['expires_at'])&&strtotime((string)$credential['expires_at'])<time();?><article class="acct-record credential"><span><b><?=$e((string)$credential['name'])?></b><small><?=$e((string)$credential['category'])?><?php if($credential['completed_at']):?> · verified <?=date('M j, Y',strtotime((string)$credential['completed_at']))?><?php endif;?><?php if($credential['expires_at']):?> · expires <?=date('M j, Y',strtotime((string)$credential['expires_at']))?><?php endif;?></small></span><em class="<?=$expired?'expired':'current'?>"><?=$expired?'Renew':'Current'?></em></article><?php endforeach;?></div><?php else:?><div class="acct-empty-state"><b>No verified requirements</b><span>Use the verification form to add the first credential.</span></div><?php endif;?></div><div class="acct-verify-card"><div class="acct-subhead"><div><h4>Verify requirement</h4><p>Record a background check, facility education, certification, or training completion.</p></div></div><form method="post"><input type="hidden" name="csrf_token" value="<?=$e((string)$_SESSION['accounts_csrf'])?>"><input type="hidden" name="user_id" value="<?=$accountId?>"><label>Requirement<select name="requirement_id" required><option value="">Choose requirement</option><?php foreach($requirements as $r):?><option value="<?=(int)$r['id']?>"><?=$e((string)$r['name'])?> · <?=$e((string)$r['category'])?><?=$r['expires']?' · expires':''?></option><?php endforeach;?></select></label><div class="acct-form-row"><label>Verified date<input type="date" name="completed_at" value="<?=$e($today)?>" required></label><label>Expiration <span>if required</span><input type="date" name="expires_at"></label></div><label>Internal note<input name="note" maxlength="1000" placeholder="Confirmation or record reference"></label><button name="action" value="verify_credential" type="submit">Verify requirement</button></form><a class="acct-inline-link" href="<?=$url('/admin/volunteer-development')?>">Manage requirements & training →</a></div></div><?php endif;?></section><?php endif;?>
        <?php endif;?></div></main></div><script src="<?=$url('/assets/js/unified-navigation.js')?>"></script></body></html><?php exit;
    }

    private static function audit(PDO $db,int $actor,string $event,int $subject,string $summary,array $meta=[]):void{self::auditSubject($db,$actor,$event,'user',$subject,$summary,$meta);}
    private static function auditSubject(PDO $db,int $actor,string $event,string $subjectType,int $subject,string $summary,array $meta=[]):void{$s=$db->prepare('INSERT INTO audit_events (actor_user_id,event_type,subject_type,subject_id,summary,metadata_json) VALUES (:actor,:event,:subject_type,:subject,:summary,:meta)');$s->execute(['actor'=>$actor,'event'=>$event,'subject_type'=>$subjectType,'subject'=>$subject,'summary'=>$summary,'meta'=>$meta?json_encode($meta,JSON_THROW_ON_ERROR):null]);}
    private static function absoluteUrl(string $path):string{$configured=rtrim((string)(getenv('APP_URL')?:''),'/');if($configured!==''){ $base=(string)(getenv('APP_BASE_PATH')?:'');if($base!==''&&str_ends_with(strtolower($configured),strtolower($base)))return $configured.substr($path,strlen($base));return $configured.$path;}$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$host=(string)($_SERVER['HTTP_HOST']??'localhost');return $scheme.'://'.$host.$path;}
    private static function flash(string $type,string $message):void{$_SESSION['accounts_flash']=['type'=>$type,'message'=>$message];}
    private static function redirect(string $url):never{header('Location: '.$url,true,303);exit;}
    private static function forbidden():never{http_response_code(403);exit('Restricted');}
}
