<?php

declare(strict_types=1);

require_once __DIR__ . '/AccessPolicy.php';
require_once __DIR__ . '/Database.php';
require_once __DIR__ . '/ProductionContext.php';
require_once __DIR__ . '/Auth.php';

final class AppNavigation
{
    public static function renderSidebar(string $route,string $basePath,array $user):void
    {
        $url=static fn(string $path):string=>($basePath?:'').$path;$esc=static fn(string $value):string=>htmlspecialchars($value,ENT_QUOTES,'UTF-8');$staff=AccessPolicy::isStaff($user);$approved=Auth::isApprovedMember($user);if(session_status()!==PHP_SESSION_ACTIVE)session_start();$_SESSION['production_context_csrf']??=bin2hex(random_bytes(24));$_SESSION['auth_csrf']??=bin2hex(random_bytes(24));
        $productionOptions=[];$selectedProduction=null;$hasFamily=false;$hasActiveProduction=false;
        try{$db=Database::connect(dirname(__DIR__));$memberProductions=ProductionContext::activeProductions($db,$user);$hasActiveProduction=(bool)$memberProductions;if($staff){$productionOptions=$memberProductions;$selectedProduction=ProductionContext::selected($db,$user);}$familyStmt=$db->prepare("SELECT 1 FROM family_relationships WHERE guardian_user_id=:user AND status='active' LIMIT 1");$familyStmt->execute(['user'=>(int)$user['id']]);$hasFamily=(bool)$familyStmt->fetchColumn();}catch(Throwable){}
        $memberTheatre=$approved||$hasActiveProduction||$staff;
        $isActive=static function(string $path)use($route):string{if($path==='/app')return in_array($route,['/app','/family/action','/notifications','/notification-preferences','/forms','/forms/view'],true)?' active':'';if($path==='/family-hub')return in_array($route,['/family-hub','/parent','/family/manage','/onboarding'],true)?' active':'';if($path==='/production')return in_array($route,['/production','/production/people','/production/groups','/production/groups/view','/production/schedule/new','/schedule','/production/day','/production/edit','/production/notices','/production/notice','/attendance','/attendance/take','/attendance/report','/admin/resources','/admin/resources/edit','/admin/files','/admin/files/edit','/playbills','/admin/playbill'],true)?' active':'';if($path==='/volunteer-readiness')return in_array($route,['/volunteer-readiness','/volunteer-shifts','/volunteer/shift','/volunteer/approvals','/volunteer/training','/volunteer/history'],true)?' active':'';return($route===$path||str_starts_with($route,rtrim($path,'/').'/'))?' active':'';};?>
        <aside class="unified-sidebar" data-unified-sidebar><div class="unified-sidebar-head"><a class="unified-brand" href="<?=$url('/app')?>"><span>C</span><b>CTSMD <small>CONNECT</small></b></a><button class="unified-close" type="button" data-nav-close aria-label="Close navigation">×</button></div><nav class="unified-nav" aria-label="Primary navigation">
        <a class="unified-nav-item<?=$isActive('/app')?>" href="<?=$url('/app')?>"><i>⌂</i><span><b>Home</b><small><?=$approved?'Today & attention':'Account & membership status'?></small></span></a>
        <?php if($hasFamily):?><a class="unified-nav-item<?=$isActive('/family-hub')?>" href="<?=$url('/family-hub')?>"><i>♟</i><span><b>Family</b><small>Children, calls & forms</small></span></a><?php endif;?>
        <?php if(!$approved&&!$staff):?><a class="unified-nav-item<?=$route==='/family/manage'?' active':''?>" href="<?=$url('/family/manage')?>"><i>✓</i><span><b>Membership pending</b><small>Manage household while CTSMD reviews</small></span></a><?php endif;?>
        <?php if($memberTheatre):?><span class="unified-nav-label">Theatre</span>
        <?php if($staff&&$productionOptions):?><form class="unified-production-switcher" method="post" action="<?=$url('/production/select')?>"><input type="hidden" name="csrf_token" value="<?=$esc((string)$_SESSION['production_context_csrf'])?>"><input type="hidden" name="return_to" value="<?=$esc($route)?>"><label for="unified-production-select">Working production</label><select id="unified-production-select" name="production_id" onchange="this.form.submit()"><?php foreach($productionOptions as $production):?><option value="<?=(int)$production['id']?>"<?=$selectedProduction&&(int)$selectedProduction['id']===(int)$production['id']?' selected':''?>><?=$esc((string)$production['title'])?><?=!empty($production['season'])?' · '.$esc((string)$production['season']):''?></option><?php endforeach;?></select></form><?php endif;?>
        <?php if($staff):?><a class="unified-nav-item<?=$isActive('/production')?>" href="<?=$url('/production')?>"><i>★</i><span><b>Production</b><small><?=$selectedProduction?$esc((string)$selectedProduction['title']):'Schedule, calls & operations'?></small></span></a><?php endif;?>
        <?php if($hasActiveProduction||$staff):?><a class="unified-nav-item<?=$isActive('/calendar')?>" href="<?=$url('/calendar')?>"><i>◫</i><span><b>Calendar</b><small>All active shows & conflicts</small></span></a><?php endif;?>
        <?php if($approved||$hasActiveProduction||$staff):?><a class="unified-nav-item<?=$isActive('/resources')?>" href="<?=$url('/resources')?>"><i>▤</i><span><b>Resources</b><small><?=$approved?'CTSMD + active productions':'Across all your active shows'?></small></span></a><a class="unified-nav-item<?=$isActive('/files')?>" href="<?=$url('/files')?>"><i>▣</i><span><b>Files</b><small><?=$approved?'CTSMD + active productions':'Across all your active shows'?></small></span></a><?php endif;?>
        <?php if($approved||$hasActiveProduction):?><a class="unified-nav-item<?=$isActive('/channels')?>" href="<?=$url('/channels')?>"><i>#</i><span><b>Community</b><small><?=$approved?'General + production channels':'Production channels'?></small></span></a><a class="unified-nav-item<?=$isActive('/messages')?>" href="<?=$url('/messages')?>"><i>✉</i><span><b>Messages</b><small>All conversations for your account</small></span></a><a class="unified-nav-item<?=$isActive('/volunteer-readiness')?>" href="<?=$url('/volunteer-readiness')?>"><i>♡</i><span><b>Volunteer</b><small>Readiness, training & shifts</small></span></a><?php endif;?>
        <?php endif;?>
        <?php if($staff):?><span class="unified-nav-label">Operations</span><a class="unified-nav-item<?=$isActive('/staff')?>" href="<?=$url('/staff')?>"><i>◎</i><span><b>Staff Overview</b><small>Cross-production triage & upcoming work</small></span></a>
        <?php if(AccessPolicy::canManagePeople($user)):?><a class="unified-nav-item<?=$isActive('/people')?>" href="<?=$url('/people')?>"><i>♟</i><span><b>People</b><small>Families, roles & access</small></span></a><?php endif;?>
        <?php if(AccessPolicy::canManageProduction($user)):?><a class="unified-nav-item<?=$route==='/production/people'?' active':''?>" href="<?=$url('/production/people')?>"><i>★</i><span><b>Production roster</b><small>Cast, guardians & staff</small></span></a><a class="unified-nav-item<?=str_starts_with($route,'/production/groups')?' active':''?>" href="<?=$url('/production/groups')?>"><i>◎</i><span><b>Production groups</b><small>Cast, crew & targeted calls</small></span></a><a class="unified-nav-item<?=str_starts_with($route,'/attendance')?' active':''?>" href="<?=$url('/attendance')?>"><i>✓</i><span><b>Attendance</b><small>Roll call & absence reports</small></span></a><a class="unified-nav-item<?=$route==='/production/schedule/new'?' active':''?>" href="<?=$url('/production/schedule/new')?>"><i>＋</i><span><b>Add schedule item</b><small>Rehearsal, performance or call</small></span></a><a class="unified-nav-item<?=str_starts_with($route,'/admin/productions')?' active':''?>" href="<?=$url('/admin/productions')?>"><i>◷</i><span><b>Productions & seasons</b><small>Create, activate & archive</small></span></a><?php endif;?>
        <?php if(AccessPolicy::canManageCommunity($user)):?><a class="unified-nav-item<?=str_starts_with($route,'/admin/channels')?' active':''?>" href="<?=$url('/admin/channels')?>"><i>#</i><span><b>Community Operations</b><small>Channels & posting rules</small></span></a><?php endif;?>
        <?php if(AccessPolicy::canModerateCommunity($user)):?><a class="unified-nav-item<?=str_starts_with($route,'/admin/moderation')?' active':''?>" href="<?=$url('/admin/moderation/terms')?>"><i>◇</i><span><b>Community moderation</b><small>Term rules & review queue</small></span></a><?php endif;?>
        <?php if(AccessPolicy::canManageCommunity($user)):?><a class="unified-nav-item<?=str_starts_with($route,'/admin/teams')||$route==='/admin/private-channel'?' active':''?>" href="<?=$url('/admin/teams')?>"><i>◎</i><span><b>Teams & private rooms</b><small>Reusable groups & selected members</small></span></a><?php endif;?>
        <?php if(AccessPolicy::canManageResources($user)):?><a class="unified-nav-item<?=str_starts_with($route,'/admin/member-resources')?' active':''?>" href="<?=$url('/admin/member-resources')?>"><i>◇</i><span><b>Member Resource Operations</b><small>CTSMD-wide approved-member library</small></span></a><a class="unified-nav-item<?=str_starts_with($route,'/admin/resources')?' active':''?>" href="<?=$url('/admin/resources')?>"><i>▤</i><span><b>Resource Operations</b><small>Working-production links & notes</small></span></a><a class="unified-nav-item<?=str_starts_with($route,'/admin/files')?' active':''?>" href="<?=$url('/admin/files')?>"><i>▣</i><span><b>File Operations</b><small>Working-production uploads & versions</small></span></a><?php endif;?>
        <?php if(AccessPolicy::canManageVolunteers($user)):?><a class="unified-nav-item<?=str_starts_with($route,'/admin/volunteer-shifts')||str_starts_with($route,'/admin/volunteer-approvals')?' active':''?>" href="<?=$url('/admin/volunteer-shifts')?>"><i>♡</i><span><b>Volunteer Operations</b><small>Shifts, approvals & staffing</small></span></a><a class="unified-nav-item<?=$route==='/admin/volunteer-development'?' active':''?>" href="<?=$url('/admin/volunteer-development')?>"><i>◈</i><span><b>Volunteer Development</b><small>Hours, training & credentials</small></span></a><?php endif;?>
        <?php if(AccessPolicy::canManageForms($user)):?><a class="unified-nav-item<?=str_starts_with($route,'/admin/forms')&&!in_array($route,['/admin/forms/build','/admin/forms/builder'],true)?' active':''?>" href="<?=$url('/admin/forms/manage')?>"><i>✓</i><span><b>Forms Operations</b><small>Create, assign & review</small></span></a><a class="unified-nav-item<?=in_array($route,['/admin/forms/build','/admin/forms/builder'],true)?' active':''?>" href="<?=$url('/admin/forms/build')?>"><i>▦</i><span><b>Form builder</b><small>Questions, choices & signatures</small></span></a><a class="unified-nav-item<?=str_starts_with($route,'/admin/registrations')?' active':''?>" href="<?=$url('/admin/registrations')?>"><i>↗</i><span><b>Registration Operations</b><small>Public opportunities & registrants</small></span></a><?php endif;?>
        <?php if(AccessPolicy::canManageProduction($user)):?><a class="unified-nav-item<?=$route==='/production/notices'||$route==='/production/notice'?' active':''?>" href="<?=$url('/production/notices')?>"><i>↗</i><span><b>Production updates</b><small>Review & publish changes</small></span></a><?php endif;?>
        <?php if(AccessPolicy::canManageSafeguarding($user)):?><a class="unified-nav-item<?=$isActive('/safeguarding')?>" href="<?=$url('/safeguarding')?>"><i>●</i><span><b>Safeguarding</b><small>Restricted review</small></span></a><?php endif;?>
        <?php if(AccessPolicy::canManageAccounts($user)):?><a class="unified-nav-item<?=str_starts_with($route,'/admin/accounts')?' active':''?>" href="<?=$url('/admin/accounts')?>"><i>⚿</i><span><b>Account & Access</b><small>Membership approval, roles & sign-in</small></span></a><a class="unified-nav-item<?=$route==='/admin/email'?' active':''?>" href="<?=$url('/admin/email')?>"><i>✉</i><span><b>Email Operations</b><small>Queue, delivery & failures</small></span></a><?php endif;?>
        <?php endif;?></nav><div class="unified-sidebar-foot"><a href="<?=$url('/notifications')?>">Notifications</a><a href="<?=$url('/notification-preferences')?>">Email preferences</a><?php if(AccessPolicy::localIdentitySwitchEnabled()):?><a href="<?=$url('/dev/identity')?>">Switch test identity</a><?php endif;?><div class="unified-user"><i><?=$esc((string)$user['initials'])?></i><span><b><?=$esc((string)$user['name'])?></b><small><?=$esc((string)$user['role'])?><?=$approved?' · CTSMD member':' · Membership pending'?></small></span></div><form method="post" action="<?=$url('/logout')?>"><input type="hidden" name="csrf_token" value="<?=$esc((string)$_SESSION['auth_csrf'])?>"><button type="submit">Sign out</button></form></div></aside><div class="unified-nav-scrim" data-nav-scrim></div><?php
    }

    public static function renderHeader(string $eyebrow,string $title,string $basePath,?array $subnav=null):void
    {
        $url=static fn(string $path):string=>($basePath?:'').$path;$esc=static fn(string $value):string=>htmlspecialchars($value,ENT_QUOTES,'UTF-8');?><header class="unified-header"><button class="unified-menu" type="button" data-nav-open aria-label="Open navigation">☰</button><div class="unified-title"><small><?=$esc($eyebrow)?></small><h1><?=$esc($title)?></h1></div><div class="unified-utilities"><a href="<?=$url('/notifications')?>">Notifications</a><span class="unified-avatar"><?=$esc(substr((string)$title,0,1))?></span></div></header><?php if($subnav):?><nav class="unified-subnav" aria-label="Section navigation"><?php foreach($subnav as $item):?><a href="<?=$url($item['href'])?>"<?=!empty($item['active'])?' class="active"':''?>><?=$esc($item['label'])?></a><?php endforeach;?></nav><?php endif;?><?php
    }
}
