<?php

declare(strict_types=1);

require_once __DIR__ . '/Database.php';
require_once __DIR__ . '/Auth.php';
require_once __DIR__ . '/AppNavigation.php';
require_once __DIR__ . '/AccessPolicy.php';

final class FormExperience
{
    private const ROUTES=['/forms','/forms/view','/admin/forms','/admin/forms/review'];
    public static function handles(string $route):bool{return in_array($route,self::ROUTES,true);}

    public static function render(string $route,string $basePath):never
    {
        Auth::startSession();$db=Database::connect(dirname(__DIR__));$user=Auth::currentUser($db);if(!$user)self::redirect(($basePath?:'').'/login');$_SESSION['forms_csrf']??=bin2hex(random_bytes(24));
        $staffRoute=str_starts_with($route,'/admin/forms');if($staffRoute&&!AccessPolicy::isStaff($user))self::forbidden($basePath,$user);
        if($_SERVER['REQUEST_METHOD']==='POST'){
            if($route==='/forms/view')self::handleSubmission($db,$user,$basePath);
            if($route==='/admin/forms/review')self::handleReview($db,$user,$basePath);
        }
        $assignment=null;$review=null;
        if($route==='/forms/view'){$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:0;$assignment=self::assignment($db,(int)$user['id'],(int)$id);}
        elseif($route==='/admin/forms/review'){$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:0;$review=self::reviewItem($db,(int)$id);}
        self::page($route,$basePath,$db,$user,$assignment,$review);
    }

    private static function handleSubmission(PDO $db,array $user,string $basePath):never
    {
        self::assertCsrf();$assignmentId=filter_input(INPUT_POST,'assignment_id',FILTER_VALIDATE_INT)?:0;
        try{self::submit($db,$user,(int)$assignmentId,$_POST);self::flash('success','Your form response was submitted.');}
        catch(RuntimeException $e){self::flash('error',$e->getMessage());self::redirect($basePath.'/forms/view?id='.(int)$assignmentId);}
        self::redirect($basePath.'/forms');
    }

    private static function submit(PDO $db,array $user,int $assignmentId,array $input):void
    {
        if($assignmentId<1)throw new RuntimeException('That form assignment could not be found.');
        $ack=isset($input['acknowledgment'])?1:0;$signature=trim((string)($input['typed_signature']??''));$response=trim((string)($input['response_text']??''));
        $db->beginTransaction();
        try{
            $stmt=$db->prepare("SELECT fa.id,fa.form_id,fa.user_id,fa.status,f.title,f.completion_mode,f.review_required FROM form_assignments fa JOIN forms f ON f.id=fa.form_id WHERE fa.id=:id AND fa.user_id=:user AND f.active=1 FOR UPDATE");$stmt->execute(['id'=>$assignmentId,'user'=>(int)$user['id']]);$assignment=$stmt->fetch();
            if(!$assignment)throw new RuntimeException('That form is not assigned to you.');if($assignment['status']==='completed')throw new RuntimeException('This form is already complete.');if(!$ack)throw new RuntimeException('Confirm that you reviewed the form before submitting.');
            if($assignment['completion_mode']==='signature'&&($signature===''||mb_strlen($signature)>190))throw new RuntimeException('Enter your typed signature before submitting.');
            if($assignment['completion_mode']==='submission'&&($response===''||mb_strlen($response)>5000))throw new RuntimeException('Enter the requested information before submitting.');
            $existing=$db->prepare('SELECT id FROM form_submissions WHERE assignment_id=:assignment FOR UPDATE');$existing->execute(['assignment'=>$assignmentId]);$submissionId=(int)($existing->fetchColumn()?:0);
            if($submissionId){$db->prepare("UPDATE form_submissions SET acknowledgment=:ack,typed_signature=:signature,response_text=:response,status='submitted',reviewer_user_id=NULL,reviewer_note=NULL,submitted_at=CURRENT_TIMESTAMP,reviewed_at=NULL WHERE id=:id")->execute(['ack'=>$ack,'signature'=>$signature!==''?$signature:null,'response'=>$response!==''?$response:null,'id'=>$submissionId]);}
            else{$db->prepare("INSERT INTO form_submissions (assignment_id,form_id,submitted_by_user_id,acknowledgment,typed_signature,response_text,status) VALUES (:assignment,:form,:user,:ack,:signature,:response,'submitted')")->execute(['assignment'=>$assignmentId,'form'=>(int)$assignment['form_id'],'user'=>(int)$user['id'],'ack'=>$ack,'signature'=>$signature!==''?$signature:null,'response'=>$response!==''?$response:null]);$submissionId=(int)$db->lastInsertId();}
            $next=(bool)$assignment['review_required']?'requires_review':'completed';$completed=$next==='completed'?date('Y-m-d H:i:s'):null;$db->prepare('UPDATE form_assignments SET status=:status,completed_at=:completed WHERE id=:id')->execute(['status'=>$next,'completed'=>$completed,'id'=>$assignmentId]);if($next==='completed')$db->prepare("UPDATE form_submissions SET status='approved',reviewed_at=CURRENT_TIMESTAMP WHERE id=:id")->execute(['id'=>$submissionId]);
            self::audit($db,(int)$user['id'],'form.submitted','form_assignment',$assignmentId,'Submitted assigned form.',['form_id'=>(int)$assignment['form_id'],'submission_id'=>$submissionId,'review_required'=>(bool)$assignment['review_required'],'resulting_status'=>$next]);$db->commit();
        }catch(Throwable $e){if($db->inTransaction())$db->rollBack();if($e instanceof RuntimeException)throw $e;throw new RuntimeException('The form could not be submitted.');}
    }

    private static function handleReview(PDO $db,array $user,string $basePath):never
    {
        if(!AccessPolicy::isStaff($user))self::forbidden($basePath,$user);self::assertCsrf();$submissionId=filter_input(INPUT_POST,'submission_id',FILTER_VALIDATE_INT)?:0;$decision=(string)($_POST['decision']??'');$note=trim((string)($_POST['reviewer_note']??''));
        try{self::reviewSubmission($db,$user,(int)$submissionId,$decision,$note);self::flash('success',$decision==='approve'?'Form approved.':'Form returned to the assignee.');}
        catch(RuntimeException $e){self::flash('error',$e->getMessage());self::redirect($basePath.'/admin/forms/review?id='.(int)$submissionId);}
        self::redirect($basePath.'/admin/forms');
    }

    private static function reviewSubmission(PDO $db,array $user,int $submissionId,string $decision,string $note):void
    {
        if($submissionId<1||!in_array($decision,['approve','reject'],true))throw new RuntimeException('Choose a valid review decision.');if(mb_strlen($note)>2000)throw new RuntimeException('Keep the review note under 2,000 characters.');
        $db->beginTransaction();
        try{
            $stmt=$db->prepare("SELECT fs.id,fs.assignment_id,fs.submitted_by_user_id,fs.status,f.title FROM form_submissions fs JOIN forms f ON f.id=fs.form_id WHERE fs.id=:id FOR UPDATE");$stmt->execute(['id'=>$submissionId]);$submission=$stmt->fetch();if(!$submission||$submission['status']!=='submitted')throw new RuntimeException('That form is no longer waiting for review.');
            $approved=$decision==='approve';$db->prepare('UPDATE form_submissions SET status=:status,reviewer_user_id=:reviewer,reviewer_note=:note,reviewed_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['status'=>$approved?'approved':'rejected','reviewer'=>(int)$user['id'],'note'=>$note!==''?$note:null,'id'=>$submissionId]);$db->prepare('UPDATE form_assignments SET status=:status,completed_at=:completed WHERE id=:id')->execute(['status'=>$approved?'completed':'missing','completed'=>$approved?date('Y-m-d H:i:s'):null,'id'=>(int)$submission['assignment_id']]);
            $title=$approved?'Form approved · '.$submission['title']:'Form needs another look · '.$submission['title'];$body=$approved?'Your submitted form was reviewed and approved.':'Your submitted form was returned for an update.'.($note!==''?' Reviewer note: '.$note:'');self::notify($db,(int)$submission['submitted_by_user_id'],'form_review',$submissionId,$title,$body,'/forms/view?id='.(int)$submission['assignment_id']);
            self::audit($db,(int)$user['id'],$approved?'form.approved':'form.rejected','form_submission',$submissionId,$approved?'Approved submitted form.':'Returned submitted form for correction.',['assignment_id'=>(int)$submission['assignment_id'],'submitted_by_user_id'=>(int)$submission['submitted_by_user_id'],'reviewer_note'=>$note!==''?$note:null]);$db->commit();
        }catch(Throwable $e){if($db->inTransaction())$db->rollBack();if($e instanceof RuntimeException)throw $e;throw new RuntimeException('The review decision could not be saved.');}
    }

    private static function assignments(PDO $db,int $userId):array{$stmt=$db->prepare("SELECT fa.id,fa.status,fa.due_at,fa.completed_at,f.title,f.form_type,f.completion_mode,f.review_required,fs.status submission_status,fs.submitted_at FROM form_assignments fa JOIN forms f ON f.id=fa.form_id LEFT JOIN form_submissions fs ON fs.assignment_id=fa.id WHERE fa.user_id=:user AND f.active=1 ORDER BY CASE fa.status WHEN 'missing' THEN 1 WHEN 'due_soon' THEN 2 WHEN 'requires_review' THEN 3 ELSE 4 END,fa.due_at,fa.id");$stmt->execute(['user'=>$userId]);return $stmt->fetchAll();}
    private static function assignment(PDO $db,int $userId,int $id):?array{if($id<1)return null;$stmt=$db->prepare("SELECT fa.id,fa.status,fa.due_at,fa.completed_at,f.id form_id,f.title,f.form_type,f.instructions,f.completion_mode,f.review_required,fs.id submission_id,fs.status submission_status,fs.typed_signature,fs.response_text,fs.reviewer_note,fs.submitted_at,fs.reviewed_at FROM form_assignments fa JOIN forms f ON f.id=fa.form_id LEFT JOIN form_submissions fs ON fs.assignment_id=fa.id WHERE fa.id=:id AND fa.user_id=:user AND f.active=1 LIMIT 1");$stmt->execute(['id'=>$id,'user'=>$userId]);return $stmt->fetch()?:null;}
    private static function reviewQueue(PDO $db):array{return $db->query("SELECT fs.id,fs.assignment_id,fs.submitted_at,f.title,f.form_type,CONCAT(u.first_name,' ',u.last_name) assignee,u.initials FROM form_submissions fs JOIN form_assignments fa ON fa.id=fs.assignment_id JOIN forms f ON f.id=fs.form_id JOIN users u ON u.id=fs.submitted_by_user_id WHERE fs.status='submitted' AND f.review_required=1 ORDER BY fs.submitted_at,fs.id")->fetchAll();}
    private static function reviewItem(PDO $db,int $id):?array{if($id<1)return null;$stmt=$db->prepare("SELECT fs.id,fs.assignment_id,fs.acknowledgment,fs.typed_signature,fs.response_text,fs.status,fs.submitted_at,fs.reviewer_note,f.title,f.form_type,f.instructions,f.completion_mode,CONCAT(u.first_name,' ',u.last_name) assignee,u.initials,u.display_role assignee_role FROM form_submissions fs JOIN forms f ON f.id=fs.form_id JOIN users u ON u.id=fs.submitted_by_user_id WHERE fs.id=:id LIMIT 1");$stmt->execute(['id'=>$id]);return $stmt->fetch()?:null;}
    private static function audit(PDO $db,int $actor,string $event,string $type,int $id,string $summary,array $meta):void{$stmt=$db->prepare('INSERT INTO audit_events (actor_user_id,event_type,subject_type,subject_id,summary,metadata_json) VALUES (:actor,:event,:type,:id,:summary,:meta)');$stmt->execute(['actor'=>$actor,'event'=>$event,'type'=>$type,'id'=>$id,'summary'=>$summary,'meta'=>json_encode($meta,JSON_THROW_ON_ERROR)]);}
    private static function notify(PDO $db,int $recipient,string $type,int $source,string $title,string $body,string $path):void{$stmt=$db->prepare("INSERT INTO app_notifications (recipient_user_id,source_type,source_id,title,body,action_path) VALUES (:recipient,:type,:source,:title,:body,:path) ON DUPLICATE KEY UPDATE title=VALUES(title),body=VALUES(body),action_path=VALUES(action_path),read_at=NULL,created_at=CURRENT_TIMESTAMP");$stmt->execute(['recipient'=>$recipient,'type'=>$type,'source'=>$source,'title'=>$title,'body'=>$body,'path'=>$path]);}
    private static function assertCsrf():void{if(!hash_equals((string)($_SESSION['forms_csrf']??''),(string)($_POST['csrf_token']??'')))throw new RuntimeException('Your session token expired. Please try again.');}
    private static function flash(string $type,string $message):void{$_SESSION['forms_flash']=['type'=>$type,'message'=>$message];}

    private static function page(string $route,string $basePath,PDO $db,array $user,?array $assignment,?array $review):never
    {
        $url=static fn(string $p):string=>($basePath?:'').$p;$e=static fn(string $v):string=>htmlspecialchars($v,ENT_QUOTES,'UTF-8');$flash=$_SESSION['forms_flash']??null;unset($_SESSION['forms_flash']);$staff=AccessPolicy::isStaff($user);$my=self::assignments($db,(int)$user['id']);$queue=$staff?self::reviewQueue($db):[];
        $title=match($route){'/forms'=>'My forms','/forms/view'=>$assignment['title']??'Form','/admin/forms'=>'Forms review','/admin/forms/review'=>$review['title']??'Review form',default=>'Forms'};$sub=[['label'=>'My forms','href'=>'/forms','active'=>in_array($route,['/forms','/forms/view'],true)]];if($staff)$sub[]=['label'=>'Review queue','href'=>'/admin/forms','active'=>in_array($route,['/admin/forms','/admin/forms/review'],true)];
        header('Content-Type:text/html; charset=utf-8');?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=$e($title)?> · CTSMD Connect</title><link rel="stylesheet" href="<?=$url('/assets/css/app.css')?>"><link rel="stylesheet" href="<?=$url('/assets/css/unified-navigation.css')?>"><link rel="stylesheet" href="<?=$url('/assets/css/forms-implementation.css')?>"></head><body class="app-body"><div class="unified-shell"><?php AppNavigation::renderSidebar($route,$basePath,$user);?><main class="unified-main"><?php AppNavigation::renderHeader('Forms',$title,$basePath,$sub);?><div class="forms-page"><?php if($flash):?><div class="forms-flash <?=$e($flash['type'])?>"><?=$e($flash['message'])?></div><?php endif;?>
        <?php if($route==='/forms'):?><section class="forms-hero"><div><small>ASSIGNED TO YOU</small><h2>Paperwork without the paper chase.</h2><p>Open requirements, acknowledgments, signatures, and submissions stay together with their current review status.</p></div><b><?=count(array_filter($my,static fn(array $a):bool=>$a['status']!=='completed'))?></b></section><div class="forms-list"><?php if(!$my):?><section class="forms-empty"><b>No forms assigned.</b></section><?php else:foreach($my as $item):?><a class="forms-card <?=$e($item['status'])?>" href="<?=$url('/forms/view?id='.(int)$item['id'])?>"><span class="forms-icon"><?=$item['completion_mode']==='signature'?'✎':($item['completion_mode']==='submission'?'▤':'✓')?></span><div><small><?=$e(strtoupper(str_replace('_',' ',$item['form_type'])))?></small><h3><?=$e($item['title'])?></h3><p><?=$item['due_at']?'Due '.$e(date('M j, Y',strtotime($item['due_at']))):'No due date'?> · <?=$item['review_required']?'Staff review required':'Completes on submission'?></p></div><em><?=$e(ucwords(str_replace('_',' ',$item['status'])))?></em></a><?php endforeach;endif;?></div>
        <?php elseif($route==='/forms/view'):?><?php if(!$assignment):?><section class="forms-empty"><b>Form not found.</b><p>This assignment may not belong to your account.</p><a class="button" href="<?=$url('/forms')?>">Back to forms</a></section><?php else:$complete=$assignment['status']==='completed';$waiting=$assignment['submission_status']==='submitted';?><section class="forms-detail-head"><div><small><?=$e(strtoupper(str_replace('_',' ',$assignment['form_type'])))?></small><h2><?=$e($assignment['title'])?></h2><p><?=$e((string)$assignment['instructions'])?></p></div><span><?=$e(ucwords(str_replace('_',' ',$assignment['status'])))?></span></section><div class="forms-detail-grid"><section class="forms-paper"><h3>Required response</h3><?php if($complete):?><div class="forms-complete"><b>✓ Complete</b><p>This assignment is complete.</p><?php if($assignment['typed_signature']):?><span>Signed: <?=$e($assignment['typed_signature'])?></span><?php endif;?></div><?php elseif($waiting):?><div class="forms-waiting"><b>Submitted for review</b><p>Staff review is required before this assignment can be marked complete.</p></div><?php else:?><form method="post" class="forms-response"><input type="hidden" name="csrf_token" value="<?=$e((string)$_SESSION['forms_csrf'])?>"><input type="hidden" name="assignment_id" value="<?=(int)$assignment['id']?>"><?php if($assignment['completion_mode']==='signature'):?><label>Typed signature<input name="typed_signature" maxlength="190" autocomplete="name" required></label><?php elseif($assignment['completion_mode']==='submission'):?><label>Requested information<textarea name="response_text" maxlength="5000" rows="8" required></textarea></label><?php endif;?><label class="forms-check"><input type="checkbox" name="acknowledgment" value="1" required><span>I confirm that I reviewed this form and that the information or acknowledgment I am submitting is accurate.</span></label><button class="button" type="submit"><?=$assignment['review_required']?'Submit for review':'Complete form'?></button></form><?php endif;?><?php if($assignment['submission_status']==='rejected'):?><div class="forms-returned"><b>Returned for update</b><p><?=$e($assignment['reviewer_note']?:'Staff requested an updated submission.')?></p></div><?php endif;?></section><aside class="forms-meta"><small>ASSIGNMENT</small><span><b>Due</b><?=$assignment['due_at']?$e(date('M j, Y',strtotime($assignment['due_at']))):'No due date'?></span><span><b>Response</b><?=$e(ucfirst($assignment['completion_mode']))?></span><span><b>Review</b><?=$assignment['review_required']?'Staff approval required':'Automatic completion'?></span><a href="<?=$url('/forms')?>">← All forms</a></aside></div><?php endif;?>
        <?php elseif($route==='/admin/forms'):?><section class="forms-hero staff"><div><small>STAFF OPERATIONS</small><h2>Forms review queue</h2><p>Submissions configured for review appear here.</p></div><b><?=count($queue)?></b></section><div class="forms-review-list"><?php if(!$queue):?><section class="forms-empty"><b>Queue clear.</b></section><?php else:foreach($queue as $item):?><a href="<?=$url('/admin/forms/review?id='.(int)$item['id'])?>"><i><?=$e($item['initials'])?></i><div><small><?=$e(strtoupper(str_replace('_',' ',$item['form_type'])))?></small><h3><?=$e($item['title'])?></h3><p><?=$e($item['assignee'])?> · Submitted <?=$e(date('M j · g:i A',strtotime($item['submitted_at'])))?></p></div><span>Review →</span></a><?php endforeach;endif;?></div>
        <?php else:?><?php if(!$review):?><section class="forms-empty"><b>Submission not found.</b><a class="button" href="<?=$url('/admin/forms')?>">Back to queue</a></section><?php else:?><section class="forms-detail-head"><div><small>STAFF REVIEW</small><h2><?=$e($review['title'])?></h2><p><?=$e($review['assignee'])?> · <?=$e($review['assignee_role'])?></p></div><span><?=$e(ucfirst($review['status']))?></span></section><div class="forms-detail-grid"><section class="forms-paper"><h3>Submitted response</h3><p class="forms-instructions"><?=$e((string)$review['instructions'])?></p><?php if($review['typed_signature']):?><div class="forms-answer"><small>TYPED SIGNATURE</small><b><?=$e($review['typed_signature'])?></b></div><?php endif;?><?php if($review['response_text']):?><div class="forms-answer"><small>RESPONSE</small><p><?=nl2br($e($review['response_text']))?></p></div><?php endif;?><div class="forms-answer"><small>ACKNOWLEDGMENT</small><b><?=$review['acknowledgment']?'Confirmed':'Not confirmed'?></b></div></section><aside class="forms-review-decision"><small>DECISION</small><?php if($review['status']!=='submitted'):?><h3>Already reviewed</h3><?php else:?><form method="post"><input type="hidden" name="csrf_token" value="<?=$e((string)$_SESSION['forms_csrf'])?>"><input type="hidden" name="submission_id" value="<?=(int)$review['id']?>"><label>Review note<textarea name="reviewer_note" rows="5" maxlength="2000"></textarea></label><button class="button" type="submit" name="decision" value="approve">Approve form</button><button class="button secondary" type="submit" name="decision" value="reject">Return for update</button></form><?php endif;?><a href="<?=$url('/admin/forms')?>">← Review queue</a></aside></div><?php endif;?><?php endif;?></div></main></div><script src="<?=$url('/assets/js/unified-navigation.js')?>"></script></body></html><?php exit;
    }

    private static function forbidden(string $basePath,array $user):never{http_response_code(403);header('Content-Type:text/plain; charset=utf-8');echo 'Staff only';exit;}
    private static function redirect(string $url):never{header('Location: '.$url,true,303);exit;}
}
