<?php

declare(strict_types=1);

require_once __DIR__ . '/Database.php';
require_once __DIR__ . '/RegistrationService.php';
require_once __DIR__ . '/Auth.php';

final class PublicExperience
{
    private const ROUTES=['/','/register','/register/manage'];
    public static function handles(string $route):bool{return in_array($route,self::ROUTES,true);}

    public static function render(string $route,string $basePath):never
    {
        Auth::startSession();$db=Database::connect(dirname(__DIR__));$_SESSION['public_registration_csrf']??=bin2hex(random_bytes(24));
        if($_SERVER['REQUEST_METHOD']==='POST')self::handlePost($db,$route,$basePath);
        if($route==='/')self::landing($db,$basePath);
        if($route==='/register/manage')self::manage($db,$basePath);
        self::registration($db,$basePath);
    }

    private static function handlePost(PDO $db,string $route,string $basePath):never
    {
        if(!hash_equals((string)($_SESSION['public_registration_csrf']??''),(string)($_POST['csrf_token']??''))){self::flash('error','Your form session expired. Please try again.');self::redirect($basePath.($route==='/register/manage'?'/register/manage':'/register'));}
        try{
            if($route==='/register'){
                $slug=trim((string)($_POST['slug']??''));$opportunity=RegistrationService::opportunityBySlug($db,$slug,true);if(!$opportunity)throw new RuntimeException('Registration for that signup is not currently open in CTSMD Connect.');$result=RegistrationService::submit($db,$opportunity,$_POST,$basePath);$_SESSION['public_registration_success']=['title'=>$opportunity['title'],'status'=>$result['status'],'token'=>$result['token']];self::redirect($basePath.'/register?submitted=1');
            }
            if($route==='/register/manage'){
                $token=(string)($_POST['token']??'');RegistrationService::cancelByToken($db,$token);self::flash('success','Registration cancelled.');self::redirect($basePath.'/register/manage?token='.rawurlencode($token));
            }
        }catch(RuntimeException $e){self::flash('error',$e->getMessage());$suffix=$route==='/register'?('?slug='.rawurlencode((string)($_POST['slug']??''))):('?token='.rawurlencode((string)($_POST['token']??'')));self::redirect($basePath.$route.$suffix);}
        self::redirect($basePath.'/');
    }

    private static function landing(PDO $db,string $basePath):never
    {
        $opportunities=array_slice(RegistrationService::publicOpportunities($db),0,3);$playbills=$db->query("SELECT pb.display_title,pb.subtitle,pb.public_slug,p.title production_title FROM playbills pb JOIN productions p ON p.id=pb.production_id WHERE pb.status='current' AND pb.public_slug IS NOT NULL ORDER BY pb.published_at DESC,pb.id DESC LIMIT 3")->fetchAll();
        self::head('CTSMD Connect',$basePath);?>
        <main class="public-shell"><header class="public-header"><a class="public-brand" href="<?=self::u($basePath,'/')?>"><span>C</span><b>CTSMD <small>CONNECT</small></b></a><nav><a href="<?=self::u($basePath,'/join')?>">Create account</a><a href="<?=self::u($basePath,'/register')?>">Auditions & signups</a><a class="public-login" href="<?=self::u($basePath,'/login')?>">Member sign in</a></nav></header>
        <section class="public-hero"><div><small>CHILDREN'S THEATRE OF SOUTHERN MARYLAND</small><h1>Your family’s front door to <em>CTSMD Connect.</em></h1><p>Parents and guardians start by creating their CTSMD Connect account. Once verified, you can build your household and add child profiles; CTSMD staff connects verified family members to the productions they actually participate in.</p><div class="public-actions"><a class="primary" href="<?=self::u($basePath,'/join')?>">Create your Connect account</a><a href="<?=self::u($basePath,'/login')?>">Already a member? Sign in</a></div></div><aside><span>CONNECT</span><strong>One account for the whole CTSMD experience.</strong><p>Schedules, Community, messages, forms, volunteer work and family information live behind the secure member experience. Auditions and selected public signups remain available separately when CTSMD publishes them.</p></aside></section>
        <section class="public-section"><header><div><small>ALREADY JOINING A SHOW?</small><h2>Auditions & selected signups</h2></div><a href="<?=self::u($basePath,'/register')?>">View all →</a></header><div class="public-grid"><?php if(!$opportunities):?><article class="public-empty"><b>No Connect signups are open right now.</b><p>Published auditions and selected event or interest signups will appear here.</p></article><?php endif;?><?php foreach($opportunities as $o):?><article class="public-card"><small><?=self::e(strtoupper(str_replace('_',' ',$o['opportunity_type'])))?></small><h3><?=self::e($o['title'])?></h3><p><?=self::e((string)($o['summary']?:'Registration is currently open.'))?></p><?php if($o['production_title']):?><span><?=self::e($o['production_title'])?></span><?php endif;?><a href="<?=self::u($basePath,'/register?slug='.rawurlencode($o['slug']))?>"><?=$o['is_full']?'Join waitlist':'Register'?> →</a></article><?php endforeach;?></div></section>
        <?php if($playbills):?><section class="public-section subdued"><header><div><small>ON STAGE</small><h2>Digital Playbills</h2></div></header><div class="public-grid"><?php foreach($playbills as $pb):?><article class="public-card playbill"><small>PLAYBILL</small><h3><?=self::e((string)($pb['display_title']?:$pb['production_title']))?></h3><p><?=self::e((string)($pb['subtitle']?:'Children’s Theatre of Southern Maryland'))?></p><a href="<?=self::u($basePath,'/playbill?slug='.rawurlencode($pb['public_slug']))?>">Open Playbill →</a></article><?php endforeach;?></div></section><?php endif;?>
        <footer class="public-footer"><b>CTSMD Connect</b><span>Secure theatre operations and community for CTSMD families, students, volunteers and staff.</span></footer></main><?php self::foot();
    }

    private static function registration(PDO $db,string $basePath):never
    {
        $success=$_SESSION['public_registration_success']??null;unset($_SESSION['public_registration_success']);$flash=$_SESSION['public_registration_flash']??null;unset($_SESSION['public_registration_flash']);$slug=trim((string)($_GET['slug']??''));$opportunity=$slug!==''?RegistrationService::opportunityBySlug($db,$slug,true):null;$opportunities=RegistrationService::publicOpportunities($db);
        self::head($opportunity?$opportunity['title']:'Auditions & signups',$basePath);?><main class="public-shell"><header class="public-header"><a class="public-brand" href="<?=self::u($basePath,'/')?>"><span>C</span><b>CTSMD <small>CONNECT</small></b></a><nav><a href="<?=self::u($basePath,'/join')?>">Create account</a><a href="<?=self::u($basePath,'/')?>">Home</a><a class="public-login" href="<?=self::u($basePath,'/login')?>">Member sign in</a></nav></header>
        <?php if($success):?><section class="registration-success"><small><?=$success['status']==='waitlisted'?'WAITLIST':'REGISTERED'?></small><h1><?=self::e($success['status']==='waitlisted'?'You’re on the waitlist.':'Registration received.')?></h1><p>We received the registration for <b><?=self::e($success['title'])?></b>. A confirmation email contains the private link needed to manage or cancel it.</p><a href="<?=self::u($basePath,'/register')?>">Back to auditions & signups</a></section>
        <?php elseif($slug!==''&&!$opportunity):?><section class="registration-success"><small>REGISTRATION</small><h1>This signup is not currently available in CTSMD Connect.</h1><p>It may not have opened yet, may have closed, may no longer be published, or may be handled in CTSMD’s separate registration system.</p><a href="<?=self::u($basePath,'/register')?>">View open auditions & signups</a></section>
        <?php elseif($opportunity):?><div class="registration-layout"><section class="registration-info"><small><?=self::e(strtoupper($opportunity['opportunity_type']))?></small><h1><?=self::e($opportunity['title'])?></h1><p><?=self::e((string)$opportunity['summary'])?></p><?php if($opportunity['production_title']):?><dl><div><dt>Production</dt><dd><?=self::e($opportunity['production_title'])?></dd></div><?php if($opportunity['starts_at']):?><div><dt>When</dt><dd><?=self::e(date('M j, Y · g:i A',strtotime($opportunity['starts_at'])))?></dd></div><?php endif;?><?php if($opportunity['location']):?><div><dt>Where</dt><dd><?=self::e($opportunity['location'])?></dd></div><?php endif;?></dl><?php endif;?><?php if($opportunity['details']):?><div class="registration-details"><?=nl2br(self::e($opportunity['details']))?></div><?php endif;?></section><section class="registration-form-card"><?php if($flash):?><div class="public-flash <?=$flash['type']?>"><?=self::e($flash['message'])?></div><?php endif;?><header><small><?=$opportunity['is_full']?'WAITLIST':'REGISTRATION'?></small><h2><?=$opportunity['is_full']?'Join the waitlist':'Register'?></h2><p>We only ask for information needed to process this signup.</p></header><form method="post"><input type="hidden" name="csrf_token" value="<?=self::e((string)$_SESSION['public_registration_csrf'])?>"><input type="hidden" name="slug" value="<?=self::e($opportunity['slug'])?>"><div class="field-pair"><label>Participant first name<input name="participant_first_name" maxlength="100" required></label><label>Participant last name<input name="participant_last_name" maxlength="100" required></label></div><label>Participant age group<select name="participant_age_group" required><option value="">Choose…</option><option value="under_13">Under 13</option><option value="13_17">13–17</option><option value="adult">18 or older</option></select><small>CTSMD Connect does not need a birth date for this registration.</small></label><div class="field-pair"><label>Primary contact email<input type="email" name="registrant_email" required></label><label>Primary contact phone <span>optional</span><input name="registrant_phone" maxlength="40"></label></div><fieldset><legend>Parent / guardian contact</legend><p>Required when the participant is under 18.</p><label>Parent or guardian name<input name="guardian_name" maxlength="190"></label><div class="field-pair"><label>Guardian email<input type="email" name="guardian_email"></label><label>Guardian phone <span>optional</span><input name="guardian_phone" maxlength="40"></label></div></fieldset><label>Anything staff should know about this registration? <span>optional</span><textarea name="notes" maxlength="2000" rows="4"></textarea><small>Please do not submit medical or other highly sensitive information here.</small></label><button type="submit"><?=$opportunity['is_full']?'Join waitlist':'Submit registration'?></button></form></section></div>
        <?php else:?><section class="registration-index"><header><small>CTSMD CONNECT</small><h1>Auditions & selected signups</h1><p>This page is intentionally limited. Classes, camps, workshops and the broader CTSMD program catalog continue to use the organization’s existing registration system for now.</p></header><div class="public-grid"><?php if(!$opportunities):?><article class="public-empty"><b>No Connect signups are open right now.</b><p>Check back for auditions and selected special-event or interest signups.</p></article><?php endif;?><?php foreach($opportunities as $o):?><article class="public-card"><small><?=self::e(strtoupper($o['opportunity_type']))?></small><h3><?=self::e($o['title'])?></h3><p><?=self::e((string)($o['summary']?:'Registration is open.'))?></p><?php if($o['starts_at']):?><span><?=self::e(date('M j, Y',strtotime($o['starts_at'])))?></span><?php endif;?><a href="<?=self::u($basePath,'/register?slug='.rawurlencode($o['slug']))?>"><?=$o['is_full']?'Join waitlist':'View & register'?> →</a></article><?php endforeach;?></div></section><?php endif;?></main><?php self::foot();
    }

    private static function manage(PDO $db,string $basePath):never
    {
        $token=(string)($_GET['token']??'');$submission=RegistrationService::submissionForToken($db,$token);$flash=$_SESSION['public_registration_flash']??null;unset($_SESSION['public_registration_flash']);self::head('Manage registration',$basePath);?><main class="public-shell"><header class="public-header"><a class="public-brand" href="<?=self::u($basePath,'/')?>"><span>C</span><b>CTSMD <small>CONNECT</small></b></a></header><section class="registration-success"><?php if($flash):?><div class="public-flash <?=$flash['type']?>"><?=self::e($flash['message'])?></div><?php endif;?><?php if(!$submission):?><small>REGISTRATION</small><h1>This private link is invalid.</h1><p>Use the manage link from the registration confirmation email.</p><?php else:?><small><?=self::e(strtoupper($submission['status']))?></small><h1><?=self::e($submission['opportunity_title'])?></h1><p><b><?=self::e($submission['participant_first_name'].' '.$submission['participant_last_name'])?></b> · submitted <?=self::e(date('M j, Y',strtotime($submission['submitted_at'])))?></p><?php if(!in_array($submission['status'],['cancelled','declined'],true)):?><form method="post" class="cancel-registration"><input type="hidden" name="csrf_token" value="<?=self::e((string)$_SESSION['public_registration_csrf'])?>"><input type="hidden" name="token" value="<?=self::e($token)?>"><button type="submit">Cancel registration</button></form><?php else:?><p>This registration is no longer active.</p><?php endif;?><?php endif;?><a href="<?=self::u($basePath,'/')?>">CTSMD Connect home</a></section></main><?php self::foot();
    }

    private static function head(string $title,string $basePath):void{header('Content-Type:text/html; charset=utf-8');?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#181416"><title><?=self::e($title)?> · CTSMD</title><link rel="stylesheet" href="<?=self::u($basePath,'/assets/css/public.css')?>"></head><body><?php }
    private static function foot():never{?></body></html><?php exit;}
    private static function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
    private static function u(string $base,string $path):string{return ($base?:'').$path;}
    private static function flash(string $type,string $message):void{$_SESSION['public_registration_flash']=['type'=>$type,'message'=>$message];}
    private static function redirect(string $url):never{header('Location: '.$url,true,303);exit;}
}
