<?php

declare(strict_types=1);

require_once __DIR__.'/AccessPolicy.php';

final class VolunteerVerificationService
{
    public static function issue(PDO $db,array $actor,int $userId,string $start,string $end,?string $purpose):int
    {
        if(!AccessPolicy::canManageVolunteers($actor))throw new RuntimeException('Volunteer management permission is required.');$startDate=self::date($start);$endDate=self::date($end);if($endDate<$startDate)throw new RuntimeException('The verification end date must be on or after the start date.');$s=$db->prepare("SELECT h.id,h.minutes,h.served_at,h.source_type,h.note,p.title production_title,vs.title shift_title,vs.category shift_category FROM volunteer_hour_entries h LEFT JOIN productions p ON p.id=h.production_id LEFT JOIN volunteer_shifts vs ON vs.id=h.shift_id WHERE h.user_id=:user AND h.status='verified' AND DATE(h.served_at) BETWEEN :start AND :end ORDER BY h.served_at,h.id");$s->execute(['user'=>$userId,'start'=>$startDate,'end'=>$endDate]);$rows=$s->fetchAll();$minutes=array_sum(array_map(static fn(array $r):int=>(int)$r['minutes'],$rows));if($minutes<1)throw new RuntimeException('No verified service hours exist in that date range.');$snapshot=[];foreach($rows as $r)$snapshot[]=['served_at'=>$r['served_at'],'minutes'=>(int)$r['minutes'],'production'=>$r['production_title']?:'CTSMD','shift'=>$r['shift_title']?:'Verified service','category'=>$r['shift_category']?:null,'source'=>$r['source_type']];$db->beginTransaction();try{$i=$db->prepare("INSERT INTO volunteer_service_verifications (user_id,period_start,period_end,verified_minutes,purpose,service_snapshot_json,verified_by_user_id,status) VALUES (:user,:start,:end,:minutes,:purpose,:snapshot,:actor,'issued')");$i->execute(['user'=>$userId,'start'=>$startDate,'end'=>$endDate,'minutes'=>$minutes,'purpose'=>trim((string)$purpose)!==''?trim((string)$purpose):null,'snapshot'=>json_encode($snapshot,JSON_THROW_ON_ERROR),'actor'=>(int)$actor['id']]);$id=(int)$db->lastInsertId();$code='CTSMD-SVC-'.date('Y').'-'.str_pad((string)$id,5,'0',STR_PAD_LEFT);$db->prepare('UPDATE volunteer_service_verifications SET verification_code=:code WHERE id=:id')->execute(['code'=>$code,'id'=>$id]);self::audit($db,(int)$actor['id'],'volunteer.verification_issued','volunteer_service_verification',$id,'Issued verified volunteer service record.',['user_id'=>$userId,'minutes'=>$minutes,'period_start'=>$startDate,'period_end'=>$endDate]);$db->commit();return$id;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e instanceof RuntimeException?$e:new RuntimeException('The service verification could not be issued.');}
    }

    public static function verification(PDO $db,int $id):?array{$s=$db->prepare("SELECT v.*,CONCAT(u.first_name,' ',u.last_name) volunteer_name,CONCAT(st.first_name,' ',st.last_name) verifier_name FROM volunteer_service_verifications v JOIN users u ON u.id=v.user_id JOIN users st ON st.id=v.verified_by_user_id WHERE v.id=:id LIMIT 1");$s->execute(['id'=>$id]);$r=$s->fetch();if(!$r)return null;$r['snapshot']=json_decode((string)$r['service_snapshot_json'],true)?:[];return$r;}
    public static function verificationsForUser(PDO $db,int $userId):array{$s=$db->prepare("SELECT v.*,CONCAT(st.first_name,' ',st.last_name) verifier_name FROM volunteer_service_verifications v JOIN users st ON st.id=v.verified_by_user_id WHERE v.user_id=:user ORDER BY v.verified_at DESC,v.id DESC");$s->execute(['user'=>$userId]);return$s->fetchAll();}
    public static function canViewVerification(PDO $db,array $viewer,int $id):bool{$v=self::verification($db,$id);if(!$v)return false;return(int)$v['user_id']===(int)$viewer['id']||AccessPolicy::canManageVolunteers($viewer);}

    public static function assignCoordinator(PDO $db,array $actor,int $userId,?int $productionId,string $title,?string $category):int
    {
        if(!AccessPolicy::canManageVolunteers($actor))throw new RuntimeException('Volunteer management permission is required.');$title=trim($title);$category=trim((string)$category);if($title===''||mb_strlen($title)>190)throw new RuntimeException('Enter a coordinator title.');$v=$db->prepare('SELECT 1 FROM volunteer_profiles WHERE user_id=:user AND active=1');$v->execute(['user'=>$userId]);if(!$v->fetchColumn())throw new RuntimeException('Choose an active volunteer.');if($productionId){$p=$db->prepare('SELECT 1 FROM productions WHERE id=:id');$p->execute(['id'=>$productionId]);if(!$p->fetchColumn())throw new RuntimeException('That production could not be found.');}$s=$db->prepare("INSERT INTO volunteer_coordinator_assignments (user_id,production_id,title,category,status,starts_at,assigned_by_user_id) VALUES (:user,:production,:title,:category,'active',CURRENT_TIMESTAMP,:actor)");$s->execute(['user'=>$userId,'production'=>$productionId,'title'=>$title,'category'=>$category!==''?$category:null,'actor'=>(int)$actor['id']]);$id=(int)$db->lastInsertId();self::audit($db,(int)$actor['id'],'volunteer.coordinator_assigned','volunteer_coordinator_assignment',$id,'Assigned volunteer coordinator role.',['user_id'=>$userId,'production_id'=>$productionId,'title'=>$title]);return$id;
    }
    public static function coordinatorAssignments(PDO $db,int $userId):array{$s=$db->prepare("SELECT a.*,p.title production_title FROM volunteer_coordinator_assignments a LEFT JOIN productions p ON p.id=a.production_id WHERE a.user_id=:user ORDER BY FIELD(a.status,'active','completed','inactive'),COALESCE(a.ends_at,a.starts_at,a.created_at) DESC");$s->execute(['user'=>$userId]);return$s->fetchAll();}
    public static function volunteers(PDO $db):array{return$db->query("SELECT u.id,CONCAT(u.first_name,' ',u.last_name) name FROM users u JOIN volunteer_profiles vp ON vp.user_id=u.id AND vp.active=1 WHERE u.active=1 ORDER BY u.last_name,u.first_name")->fetchAll();}
    public static function productions(PDO $db):array{return$db->query("SELECT id,title,season FROM productions ORDER BY is_active DESC,id DESC")->fetchAll();}
    private static function date(string $value):string{$d=DateTimeImmutable::createFromFormat('Y-m-d',trim($value));if(!$d||$d->format('Y-m-d')!==trim($value))throw new RuntimeException('Choose valid start and end dates.');return$d->format('Y-m-d');}
    private static function audit(PDO $db,int $actor,string $event,string $type,int $id,string $summary,array $meta):void{$s=$db->prepare('INSERT INTO audit_events (actor_user_id,event_type,subject_type,subject_id,summary,metadata_json) VALUES (:actor,:event,:type,:id,:summary,:meta)');$s->execute(['actor'=>$actor,'event'=>$event,'type'=>$type,'id'=>$id,'summary'=>$summary,'meta'=>json_encode($meta,JSON_THROW_ON_ERROR)]);}
}
